runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url : /css
  static_dir: css

- url : /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /profile/.*
  script: user_profile.app
  login: required
  auth_fail_action: redirect

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"